### ISSUE TITLE
発表用Macのローカルにデータを入れておく

### ISSUE THREAD

**Issue by mdb-konno** [MeHerBu/FR-App#33]
ネット繋がらない場合に使用する

**Comment by mdb-konno** [comment]
あ、ローカルで動かすには、Apache（MAMPがいい？）を入れなきゃだ。

**Comment by y-nishino** [comment]
MAMPと今日時点のマージされたデータを落としてきました。

**Comment by mdb-konno** [comment]
最新を落としてくださいー！
あと、オフラインのテストをお願いいたします！

**Comment by mdb-konno** [comment]
にしのちゃんが当日までやってくれる。
クローズしますー
